### ISSUE TITLE
aws eks named profile with kubeswitch store errors

### ISSUE THREAD

**Issue by shabbskagalwala** [danielfoehrKn/kubeswitch#97] opened 2023-11-09 05:42 UTC
I just came across kubeswitch and its an awesome project - thank you for this! 

After i installed kubeswitch and set up the store for eks, and tried setting an alias for the context, i keep getting this error

```
→ [11:10:17] ~  ✗ s alias dev-admin="arn:aws:eks:us-west-2:xxxx:cluster/dev"
Set alias "dev-admin" for context "arn:aws:eks:us-west-2:xxxx:cluster/dev".
→ [11:10:21] ~  ✗ Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

The shell blocks and until a return is pressed i can't proceed further. This only happens when setting aliases. Removing and listing aliases works fine. 

Note: the context does get switched, and everything works fine. It's just during the setting of aliases that causes this issue.

```
→ [11:23:01] ~  ✗ aws --version
aws-cli/2.11.1 Python/3.11.2 Darwin/23.0.0 source/arm64 prompt/off
```

**Comment by danielfoehrKn** [comment] 2023-11-29 10:45
Hi, thanks for reporting. I currently cannot reproduce this issue, so I am waiting for more people reporting this behaviour.
In the meanwhile, I am afraid, you might have to not use aliases.

**Comment by danielfoehrKn** [comment] 2024-04-14 01:45
it seems that not many people have encountered this problem, so I'll close it for now. Please comment below if you see that same problem.

**Closed by danielfoehrKn** 2024-04-14 01:45 UTC
