### ISSUE TITLE
not scanning kubeconfigs and --kubeconfig-directory option not working

### ISSUE THREAD

**Issue by KlavsKlavsen** [danielfoehrKn/kubeswitch#7] opened 2021-02-10 10:25 UTC
Running as readme suggests only shows help output ?
```
$ switch --kubeconfig-directory ~/.kube

Simple tool for switching between kubeconfig contexts. The kubectx build for people with a lot of kubeconfigs.

Usage:
  switch [flags]
  switch [command]

Available Commands:
  clean       Cleans all temporary kubeconfig files
  help        Help about any command
  hooks       Runs configured hooks

Flags:
      --config-directory string    path to the configuration file. (default "~/.kube/switch-config.yaml")
  -h, --help                       help for switch
      --kubeconfig-name string     only shows kubeconfig files with this name. Accepts wilcard arguments "*" and "?". Defaults to "config". \(default "config")
      --kubeconfig-path string     path to be recursively searched for kubeconfig files. Can be a directory on the local filesystem or a path in Vault. (default "~/.kube")
      --show-preview               show preview of the selected kubeconfig. Possibly makes sense to disable when using vault as the kubeconfig store to prevent excessive requests against the API. (default true)
      --state-directory string     path to the local directory used for storing internal state. (default "~/.kube/switch-state")
      --store string               the backing store to be searched for kubeconfig files. Can be either "filesystem" or "vault" (default "filesystem")
      --vault-api-address string   the API address of the Vault store.

Use "switch [command] --help" for more information about a command.
```
That folder contains:
```
$ ls ~/.kube 
7ejidqmfi9-k8sca  cache  http-cache  kubectx  kubens  microk8s  p-boa-kube-ca  switch-config.yaml  t-boss-ca
```
and if I run switch with no arguments.. it just says 0/0 at the bottom.. Nothing to choose from :(

**Comment by danielfoehrKn** [comment] 2021-02-10 11:09
Closing, duplicate of #6

**Closed by danielfoehrKn** 2021-02-10 11:09 UTC
