### ISSUE TITLE
Support for the new GKE auth process

### ISSUE THREAD

**Issue by dfineSvenFlock** [danielfoehrKn/kubeswitch#78] opened 2023-08-02 11:58 UTC
Hi,

Google has updated the auth process for GKE last year.

`kubeswitch` does not support the new version, I guess as after selecting a cluster and entering a kubectl command I get the following error:

```
kubectl get nodes
error: The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details
```

Is there any way to support that? 

My current workaround is to use the native GCP CLI to get the credentials

```
gcloud container clusters get-credentials <cluster> --region <region>
```

but that's why I am using `kubeswitch` in the first place :-).

Thanks!

**Comment by danielfoehrKn** [comment] 2023-08-02 12:28
Hi, I am aware of the issue, thank you. Duplicate of this [issue](https://github.com/danielfoehrKn/kubeswitch/issues/37). Will fix it when I find time for it, otherwise hoping for someone else to jump in.

**Closed by danielfoehrKn** 2023-08-02 12:28 UTC
